import React from 'react';
import Head from 'next/head'
import Header from './Header';
import styles from '../styles/Layout.module.css'

const Layout = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Ship store App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                {children}
            </main>
        </div>
    )
}

export default Layout;